#library "playerdeath"
#include "zcommon.acs"

script "PlayerRespawn" RESPAWN
{
	SetMusic("*", 0);
	FadeTo(255, 255, 255, 0.0, 0.32);
	ACS_NamedTerminate("PlayerDeath", 0);
}

script "PlayerDeath" DEATH
{
	FadeTo(0, 0, 0, 1.0, 2.0);
	SetMusic("", 0);
	delay(1);
	ActivatorSound("game/missionfail", 255);
	SetHUDSize(640, 400, 0);
	SetFont("FAILED");
	HudMessage(s: "A"; HUDMSG_PLAIN, 200, CR_UNTRANSLATED, 320.0, 300.0, 7.5);
}