#library "porthealth"
#include "zcommon.acs"

#define LOG_PORTABLEKIT		101

script "UsePortableHealth" (void)
{
	if (CheckInventory("PortableFA") > 0)
	{
		if (CheckInventory("Health") < 100 && CheckInventory("Health") > 0)
		{
			SetHudSize(640, 400, 0);
			SetFont("SMALLFONT");
			HudMessage(s: "Used Portable Medkit"; HUDMSG_PLAIN, LOG_PORTABLEKIT, CR_WHITE, 320.0, 275.0, 1.0);
			TakeInventory("PortableFA", 1);
			GiveInventory("FirstAid1", 25);
			ActivatorSound("GRABHLTH", 255);
		}
	}
}